use tauri::{command, AppHandle};
use std::collections::HashMap;
use std::fs::File;
use std::io::Write;
use zip::write::FileOptions;
use crate::commands::adb;

#[command]
pub async fn get_all_props(app: AppHandle) -> Result<HashMap<String, String>, String> {
    let output = adb::run_adb_shell(app, "getprop".into()).await?;
    let mut props = HashMap::new();
    
    // Output format: [key]: [value]
    for line in output.lines() {
        if let Some((key_part, val_part)) = line.split_once("]: [") {
            let key = key_part.trim_start_matches('[');
            let val = val_part.trim_end_matches(']');
            props.insert(key.to_string(), val.to_string());
        }
    }
    
    Ok(props)
}

#[command]
pub async fn generate_prop_module(props: HashMap<String, String>, save_path: String) -> Result<(), String> {
    let file = File::create(&save_path).map_err(|e| e.to_string())?;
    let mut zip = zip::ZipWriter::new(file);
    let options = FileOptions::default().compression_method(zip::CompressionMethod::Stored);

    // 1. module.prop
    zip.start_file("module.prop", options).map_err(|e| e.to_string())?;
    let module_prop = r#"id=cyberflash_props
name=CyberFlash Prop Editor
version=v1.0
versionCode=1
author=CyberFlash
description=Systemless properties generated by CyberFlash V2
"#;
    zip.write_all(module_prop.as_bytes()).map_err(|e| e.to_string())?;

    // 2. system.prop
    zip.start_file("system.prop", options).map_err(|e| e.to_string())?;
    for (key, value) in props {
        let line = format!("{}={}\n", key, value);
        zip.write_all(line.as_bytes()).map_err(|e| e.to_string())?;
    }

    // 3. META-INF/com/google/android/update-binary (Dummy for Magisk)
    // Actually Magisk modules just need to be a zip with module.prop. 
    // But for installation via recovery, we need update-binary.
    // For installation via Magisk App, just the zip structure is enough usually.
    // Let's add a basic updater-script just in case.
    
    // Wait, Magisk modules structure:
    // /
    //   module.prop
    //   system.prop
    //   ...
    
    // That's it. Magisk handles the rest.
    
    zip.finish().map_err(|e| e.to_string())?;
    
    Ok(())
}
